DATA:
  data_root: dataset/IQON3000
  train_data_ori: dataset/IQON3000/data/train.csv
  valid_data_ori: dataset/IQON3000/data/valid.csv
  test_data_ori: dataset/IQON3000/data/test.csv
  visual_features_dict_ori: dataset/IQON3000/feat/visualfeatures
  textural_idx_dict_ori: dataset/IQON3000/feat/textfeatures
  textural_embedding_matrix: dataset/IQON3000/feat/smallnwjc2vec
  user_map: dataset/IQON3000/data/user_map.json
  item_map: dataset/IQON3000/data/item_map.json
  visual_features_tensor: dataset/IQON3000/feat/visualfeatures_indexedtenseor
  textural_features_tensor: dataset/IQON3000/feat/textfeatures_indexedtenseor
  train_data: dataset/IQON3000/data/train_indexed.csv
  valid_data: dataset/IQON3000/data/valid_indexed.csv
  test_data: dataset/IQON3000/data/test_indexed.csv

TRAIN:
  arch: APCL
  dataset: IQON3000
  epochs: 80
  start_epoch: 0
  max_sentence: 83
  print_freq: 1
  workers: 2
  batch_size: 1024
  hidden_dim: 512
  text_feature_dim: 300
  visual_feature_dim: 2048
  textcnn_layer: 4
  with_visual: True
  with_text: True
  train_gpu: 1
  base_lr: 0.001 # learning rate
  wd: 0.00001 # weight decay
  num_interaction: 2 # choose 2 bottoms that has been chose by the given top
  patience: 5 # for early stop
  with_Nor: True # Feature Scaling
  b_PC: True # project bottom into personalization and conpatibility spaces separately
  cos: True # using cosine similairity calculate distance
  weight:  # path to initial weight (default: none)
  resume:  # 
  weight_P: 0.3
  his_select_t: False # using textual information to help to select historical bottoms
  popular_padding: True # using popular items to padding those historiacl interactions less than default number
  repeated_interact: False # only contain one interaction for those bottoms chosed by same top/user more than twice for history selection
  save_path: saved/IQON3000/APCL
  evaluate: True
  batch_size_val: 1024
  start_epoch: 0
  num_his: 2
  num_interact: 2
  save_freq: 1
  user_num: 300 
  top_u: 2 # top ranked user number in user similarity calculation
  att: True # suing self_att
  with_self_his: False 
  u_pb_num: 2 # user chosed top-ranked matching items
  uu_w: 1 # weight of user similarity branch
  uu_v_w: 0.5 # weight of visual modality
  use_weighted_loss: False # using weighted infoNCE loss
  temperature: 0.1 
  w_infoNCE: 0.05 #weight of infoNCE LOSS

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_batch_size: 1024
  test_gpu: [0]
  has_prediction: False # has prediction already or not
  model_path: saved/IQON3000/APCL/   # evaluation model path
  save_folder: saved/IQON3000/APCL/result/   #test results save folder
  test_distributed: False